gpio: mpfs: fix an incompatible pointer warning
Clang complains:
../drivers/gpio/gpio-mpfs.c:269:13: error: assigning to 'struct irq_chip *' from 'const struct irq_chip *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        girq->chip = &mpfs_gpio_irqchip;
                   ^ ~~~~~~~~~~~~~~~~~~
1 error generated.

Drop the const qualifier to avoid breaking the allmodconfig build.

Fixes: 66113bc92a4f ("gpio: mpfs: fix missed interrupts while PM is enabled")
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>