vfs: dcache: Export d_ancestor to modules
With OverlayFS v22 I get the following build error when
CONFIG_OVERLAYFS_FS=m

ERROR: "d_ancestor" [fs/overlayfs/overlayfs.ko] undefined!

Fix this by adding the missing export.

Signed-off-by: Miklos Szeredi <mszeredi@suse.cz>