wifi: wilc1000: remove unnecessary nullpointer check
Building with allmodconfig complains:

../drivers/net/wireless/microchip/wilc1000/bt.c:688:16: error: comparison of address of 'wilc_bt->cs' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
        if (&wilc_bt->cs != NULL)
             ~~~~~~~~~^~    ~~~~
1 error generated.

Fixes: b7dc6a0a76a1c ("wilc1000: Added BLE support")
Signed-off-by: Thomas Kopp <thomas.kopp@microchip.com>
Acked-by: Ajay Kathat <ajay.kathat@microchip.com>
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>