gpio: rda: remove unused variable
Clang complains:
../drivers/gpio/gpio-rda.c:200:22: error: unused variable 'np' [-Werror,-Wunused-variable]
        struct device_node *np = pdev->dev.of_node;
                            ^
Remove the variable.

Fixes: 6d8e9348287a ("gpio: Get rid of duplicate of_node assignment in the drivers")
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>